### ISSUE TITLE
Replace use of deprecated method causing build to fail

### ISSUE THREAD

**Issue by rabbah** [rabbah/slack-email-digest#1]
```
Traceback (most recent call last):
209  File "slack_email_digest.py", line 202, in <module>
210    main(args)
211  File "slack_email_digest.py", line 188, in main
212    channels, sendTo = filter_channels(slack, args.conf)
213  File "slack_email_digest.py", line 84, in filter_channels
214    channels = slack.channels.list().body['channels']
215  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/slacker/__init__.py", line 428, in list
216    'exclude_members': exclude_members})
217  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/slacker/__init__.py", line 120, in get
218    api, **kwargs
219  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/slacker/__init__.py", line 102, in _request
220    raise Error(response.error)
221slacker.Error: method_deprecated
222The command "python slack_email_digest.py -c apache-configuration.yaml" exited with 1.

**Comment by rabbah** [comment]
The python SDK was using an API which was deprecated this month.
The SDK itself was no longer being maintained either.
Switch to use Slack's official SDK.

Fixed by https://github.com/rabbah/slack-email-digest/commit/2f1fed047249d36da58577a0d72e9dc6254c9c06.
